version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ..
      dockerfile: hmls-services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=api-gateway
      - AUTH_SERVICE_GRPC_URL=auth-service:50051
      - APPOINTMENT_SERVICE_GRPC_URL=appointment-service:50052
      - NOTIFICATION_SERVICE_GRPC_URL=notification-service:50053
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - auth-service
      - appointment-service
      - notification-service
      - redis
    networks:
      - hmls-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ..
      dockerfile: hmls-services/auth-service/Dockerfile
    ports:
      - "8001:8001"
      - "50051:50051"
    environment:
      - SERVICE_NAME=auth-service
      - DATABASE_URL=postgresql://postgres:postgres@postgres/auth_db
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GRPC_PORT=50051
    depends_on:
      - postgres
      - redis
    networks:
      - hmls-network
    restart: unless-stopped

  # Appointment Service
  appointment-service:
    build:
      context: ..
      dockerfile: hmls-services/appointment-service/Dockerfile
    ports:
      - "8002:8002"
      - "50052:50052"
    environment:
      - SERVICE_NAME=appointment-service
      - DATABASE_URL=postgresql://postgres:postgres@postgres/appointment_db
      - REDIS_URL=redis://redis:6379/2
      - AUTH_SERVICE_GRPC_URL=auth-service:50051
      - NOTIFICATION_SERVICE_GRPC_URL=notification-service:50053
      - GRPC_PORT=50052
    depends_on:
      - postgres
      - redis
      - auth-service
    networks:
      - hmls-network
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: ..
      dockerfile: hmls-services/notification-service/Dockerfile
    ports:
      - "8003:8003"
      - "50053:50053"
    environment:
      - SERVICE_NAME=notification-service
      - REDIS_URL=redis://redis:6379/3
      - DATABASE_URL=postgresql://postgres:postgres@postgres/notification_db
      - AUTH_SERVICE_GRPC_URL=auth-service:50051
      - GRPC_PORT=50053
    depends_on:
      - postgres
      - redis
    networks:
      - hmls-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,appointment_db,notification_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-multiple-postgres-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-postgres-dbs.sh
    networks:
      - hmls-network
    restart: unless-stopped

  # Redis for caching, message queue, and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hmls-network
    restart: unless-stopped

networks:
  hmls-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 