# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.proto import appointment_pb2 as common_dot_proto_dot_appointment__pb2


class AppointmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAppointment = channel.unary_unary(
                '/appointment.AppointmentService/CreateAppointment',
                request_serializer=common_dot_proto_dot_appointment__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.GetAppointments = channel.unary_unary(
                '/appointment.AppointmentService/GetAppointments',
                request_serializer=common_dot_proto_dot_appointment__pb2.TokenRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentsResponse.FromString,
                )
        self.GetAppointment = channel.unary_unary(
                '/appointment.AppointmentService/GetAppointment',
                request_serializer=common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.UpdateAppointment = channel.unary_unary(
                '/appointment.AppointmentService/UpdateAppointment',
                request_serializer=common_dot_proto_dot_appointment__pb2.UpdateAppointmentRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
                )
        self.DeleteAppointment = channel.unary_unary(
                '/appointment.AppointmentService/DeleteAppointment',
                request_serializer=common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.StatusResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/appointment.AppointmentService/HealthCheck',
                request_serializer=common_dot_proto_dot_appointment__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_appointment__pb2.HealthCheckResponse.FromString,
                )


class AppointmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAppointment,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointments,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.TokenRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.AppointmentsResponse.SerializeToString,
            ),
            'GetAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointment,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'UpdateAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAppointment,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.UpdateAppointmentRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.AppointmentResponse.SerializeToString,
            ),
            'DeleteAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAppointment,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.StatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_proto_dot_appointment__pb2.HealthCheckRequest.FromString,
                    response_serializer=common_dot_proto_dot_appointment__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appointment.AppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppointmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/CreateAppointment',
            common_dot_proto_dot_appointment__pb2.AppointmentRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetAppointments',
            common_dot_proto_dot_appointment__pb2.TokenRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.AppointmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/GetAppointment',
            common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/UpdateAppointment',
            common_dot_proto_dot_appointment__pb2.UpdateAppointmentRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/DeleteAppointment',
            common_dot_proto_dot_appointment__pb2.AppointmentIdRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/appointment.AppointmentService/HealthCheck',
            common_dot_proto_dot_appointment__pb2.HealthCheckRequest.SerializeToString,
            common_dot_proto_dot_appointment__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
