# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.proto import auth_pb2 as common_dot_proto_dot_auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/auth.AuthService/Register',
                request_serializer=common_dot_proto_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_auth__pb2.UserResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=common_dot_proto_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_auth__pb2.TokenResponse.FromString,
                )
        self.GetCurrentUser = channel.unary_unary(
                '/auth.AuthService/GetCurrentUser',
                request_serializer=common_dot_proto_dot_auth__pb2.TokenRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_auth__pb2.UserResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=common_dot_proto_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=common_dot_proto_dot_auth__pb2.UserResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=common_dot_proto_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=common_dot_proto_dot_auth__pb2.TokenResponse.SerializeToString,
            ),
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=common_dot_proto_dot_auth__pb2.TokenRequest.FromString,
                    response_serializer=common_dot_proto_dot_auth__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Register',
            common_dot_proto_dot_auth__pb2.RegisterRequest.SerializeToString,
            common_dot_proto_dot_auth__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Login',
            common_dot_proto_dot_auth__pb2.LoginRequest.SerializeToString,
            common_dot_proto_dot_auth__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetCurrentUser',
            common_dot_proto_dot_auth__pb2.TokenRequest.SerializeToString,
            common_dot_proto_dot_auth__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
